

apiVersion: webs/v1
kind: Deployment
metadata:
  name: frontend
  namespace: roboshop
  labels:
    component: frontend
    project : roboshop
    tier : web
spec:
  replicas: 1   # Number of pod replicas
  selector:
    matchLabels:
      component: frontend
      project : roboshop
      tier : web
  template:
    metadata:
      labels:
        component: frontend
        project : roboshop
        tier : web
    spec:
      containers:
        - name: frontend
          image: revops78/frontend:v1
          
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: roboshop
  labels:
    component: frontend
    project : roboshop
    tier : web
spec:
  type: LoadBalancer
  selector:
    component: frontend
    project : roboshop
    tier : web  
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
          


