apiVersion: v1
kind: Secret
metadata:
  name: mysql
  labels:
    component: mysql
    project : roboshop
    tier : database
type: Opaque
data:
  AMQP_USER: "cm9ib3Nob3A="
  AMQP_PASS: "cm9ib3Nob3AxMjM="

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: payment
  namespace: roboshop
  labels:
    component: payment
    project : roboshop
    tier : app
data:
  CART_HOST: "cart"
  CART_PORT: "8080"
  USER_HOST: "user"
  USER_PORT: "8080"
  AMQP_HOST: "rabbitmq"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: roboshop
  labels:
    component: payment
    project : roboshop
    tier : app
spec:
  replicas: 1   # Number of pod replicas
  selector:
    matchLabels:
      component: payment
      project : roboshop
      tier : app
  template:
    metadata:
      labels:
        component: payment
        project : roboshop
        tier : app
    spec:
      containers:
        - name: payment
          image: revops78/payment:v1
          envFrom:
            - configMapRef:
                name: payment
            - secretRef:
                name: payment
---
apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: roboshop
  labels:
    component: payment
    project : roboshop
    tier : app
spec:
  selector:
    component: payment
    project : roboshop
    tier : app 
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
          


