apiVersion: v1
kind: ConfigMap
metadata:
  name: cart
  namespace: roboshop
  labels:
    component: cart
    project : roboshop
    tier : database

data:
  REDIS_HOST: "redis"
  CATALOGUE_HOST: "catalogue"
  CATALOGUE_PORT: "8080"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: roboshop
  labels:
    component: cart
    project : roboshop
    tier : database
spec:
  replicas: 1   # Number of pod replicas
  selector:
    matchLabels:
      component: cart
      project : roboshop
      tier : database
  template:
    metadata:
      labels:
        component: cart
        project : roboshop
        tier : database
    spec:
      containers:
        - name: cart
          image: revops78/cart:v1
          envFrom:
            - configMapRef:
                name: cart
---
apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: roboshop
  labels:
    component: cart
    project : roboshop
    tier : app
spec:
  selector:
    component: cart
    project : roboshop
    tier : database  
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
          


